# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 11:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('description', models.TextField(max_length=500)),
                ('time_now', models.DateTimeField(verbose_name=datetime.datetime(2018, 12, 26, 11, 46, 28, 150910, tzinfo=utc))),
            ],
        ),
    ]
